import {
  // Smileys & People
  Smile,
  Laugh,
  SmilePlus,
  Meh,
  Frown,
  Angry,
  Annoyed,
  Ghost,
  Baby,
  User,
  Users,
  Crown,
  Glasses,
  PartyPopper,
  Skull,
  BotMessageSquare,
  CircleDashed,
  BrainCircuit,
  Footprints,
  Hand,
  HandMetal,
  ThumbsUp,
  ThumbsDown,
  PersonStanding,
  Bot,
  CircleUser,
  Contact,
  BadgeCheck,

  // Hearts & Love
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Sparkles,
  Gift,
  Gem,
  Diamond,
  Ribbon,
  HeartOff,
  Sparkle,
  HandHeart,
  MessageCircleHeart,

  // Animals & Nature
  Bird,
  Bug,
  Cat,
  Dog,
  Fish,
  Flower,
  Flower2,
  Leaf,
  Trees,
  Sprout,
  TreePine,
  Turtle,
  Rabbit,
  Squirrel,
  Snail,
  PawPrint,
  TreeDeciduous,
  Shrub,
  MountainSnow,
  Waves,
  Droplets,
  Droplet,
  Shell,
  Wheat,
  Vegan,

  // Food & Drink
  Apple,
  Cherry,
  Grape,
  Banana,
  Coffee,
  Wine,
  Beer,
  Pizza,
  Cake,
  CakeSlice,
  IceCreamCone,
  Cookie,
  Croissant,
  Popcorn,
  Candy,
  Milk,
  CupSoda,
  Beef,
  Egg,
  Sandwich,
  Salad,
  Soup,
  Nut,
  Citrus,
  GlassWater,

  // Travel & Places
  Plane,
  Car,
  Ship,
  TrainFront,
  Bike,
  Globe,
  Map,
  MapPin,
  Mountain,
  Tent,
  Building,
  Home,
  Church,
  Compass,
  Anchor,
  Rocket,
  Hotel,
  Factory,
  Landmark,
  Castle,
  Fuel,
  Bus,
  Sailboat,
  Cable,
  Warehouse,
  Store,
  Hospital,
  School,
  Library,

  // Activities
  Music,
  Gamepad2,
  Dumbbell,
  Trophy,
  Medal,
  Target,
  Palette,
  Camera,
  Clapperboard,
  Mic,
  Headphones,
  Guitar,
  Dice5,
  Volleyball,
  Brush,
  PenTool,
  Ruler,
  Dice1,
  Puzzle,
  Drama,
  Piano,
  Drum,
  Speaker,
  Radio,
  Tv,
  Film,
  Projector,

  // Objects
  Key,
  Lock,
  Lightbulb,
  Phone,
  Laptop,
  Watch,
  Umbrella,
  Scissors,
  Wrench,
  Hammer,
  Bell,
  Bookmark,
  Flag,
  Mail,
  Pencil,
  Briefcase,
  Shirt,
  Wallet,
  ShoppingBag,
  Package,
  Syringe,
  Pill,
  Stethoscope,
  Scroll,
  Newspaper,
  BookOpen,
  Notebook,
  FileText,
  Clipboard,

  // Symbols
  Star,
  Sun,
  Moon,
  Cloud,
  Zap,
  Flame,
  Snowflake,
  Rainbow,
  Infinity,
  Hash,
  AtSign,
  Copyright,
  Pi,
  Omega,
  Percent,
  AlertTriangle,
  Circle,
  Square,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  ArrowUp,
  ArrowRight,
  Check,
  X,
  Plus,
  Minus,
  Equal,
  Asterisk,
  Power,
  Wifi,
  Bluetooth,
  Volume2,
  Eye,
  EyeOff,
  Shield,
  Unlock,
  Clock,
  Timer,
  Calendar,
} from 'lucide-react';

import type { EmojiEntry, EmojiCategory } from './types';

export const CATEGORIES: EmojiCategory[] = [
  'Smileys & People',
  'Hearts & Love',
  'Animals & Nature',
  'Food & Drink',
  'Travel & Places',
  'Activities',
  'Objects',
  'Symbols',
];

export const CATEGORY_ICONS: Record<EmojiCategory, typeof Smile> = {
  'Smileys & People': Smile,
  'Hearts & Love': Heart,
  'Animals & Nature': Leaf,
  'Food & Drink': Coffee,
  'Travel & Places': Globe,
  'Activities': Music,
  'Objects': Key,
  'Symbols': Star,
};

export const emojiData: EmojiEntry[] = [
  // ─── Smileys & People ────────────────────────────────────────
  { name: 'Smile', icon: Smile, keywords: ['happy', 'face', 'smiley', 'grin'], category: 'Smileys & People' },
  { name: 'Laugh', icon: Laugh, keywords: ['lol', 'haha', 'funny', 'joy'], category: 'Smileys & People' },
  { name: 'Smile Plus', icon: SmilePlus, keywords: ['add', 'happy', 'new', 'positive'], category: 'Smileys & People' },
  { name: 'Meh', icon: Meh, keywords: ['neutral', 'indifferent', 'okay', 'face'], category: 'Smileys & People' },
  { name: 'Frown', icon: Frown, keywords: ['sad', 'unhappy', 'disappointed', 'face'], category: 'Smileys & People' },
  { name: 'Angry', icon: Angry, keywords: ['mad', 'upset', 'furious', 'face'], category: 'Smileys & People' },
  { name: 'Annoyed', icon: Annoyed, keywords: ['irritated', 'frustrated', 'face'], category: 'Smileys & People' },
  { name: 'Ghost', icon: Ghost, keywords: ['spooky', 'halloween', 'spirit', 'boo'], category: 'Smileys & People' },
  { name: 'Baby', icon: Baby, keywords: ['child', 'infant', 'kid', 'newborn'], category: 'Smileys & People' },
  { name: 'User', icon: User, keywords: ['person', 'profile', 'account', 'human'], category: 'Smileys & People' },
  { name: 'Users', icon: Users, keywords: ['people', 'group', 'team', 'community'], category: 'Smileys & People' },
  { name: 'Crown', icon: Crown, keywords: ['king', 'queen', 'royal', 'winner'], category: 'Smileys & People' },
  { name: 'Glasses', icon: Glasses, keywords: ['nerd', 'smart', 'vision', 'cool'], category: 'Smileys & People' },
  { name: 'Party Popper', icon: PartyPopper, keywords: ['celebrate', 'celebration', 'confetti', 'tada'], category: 'Smileys & People' },
  { name: 'Skull', icon: Skull, keywords: ['dead', 'danger', 'death', 'skeleton'], category: 'Smileys & People' },
  { name: 'Bot', icon: BotMessageSquare, keywords: ['robot', 'ai', 'machine', 'chat'], category: 'Smileys & People' },
  { name: 'Cool', icon: CircleDashed, keywords: ['cool', 'circle', 'dashed', 'outline'], category: 'Smileys & People' },
  { name: 'Brain Circuit', icon: BrainCircuit, keywords: ['brain', 'smart', 'ai', 'intelligence', 'think'], category: 'Smileys & People' },
  { name: 'Footprints', icon: Footprints, keywords: ['feet', 'walk', 'steps', 'tracks'], category: 'Smileys & People' },
  { name: 'Hand', icon: Hand, keywords: ['wave', 'hi', 'hello', 'palm', 'stop'], category: 'Smileys & People' },
  { name: 'Rock On', icon: HandMetal, keywords: ['metal', 'rock', 'horns', 'gesture'], category: 'Smileys & People' },
  { name: 'Thumbs Up', icon: ThumbsUp, keywords: ['like', 'approve', 'good', 'yes'], category: 'Smileys & People' },
  { name: 'Thumbs Down', icon: ThumbsDown, keywords: ['dislike', 'bad', 'no', 'disapprove'], category: 'Smileys & People' },
  { name: 'Person Standing', icon: PersonStanding, keywords: ['person', 'human', 'body', 'stand'], category: 'Smileys & People' },
  { name: 'Robot', icon: Bot, keywords: ['robot', 'ai', 'bot', 'machine'], category: 'Smileys & People' },
  { name: 'Avatar', icon: CircleUser, keywords: ['user', 'profile', 'avatar', 'account'], category: 'Smileys & People' },
  { name: 'Contact', icon: Contact, keywords: ['person', 'card', 'address', 'info'], category: 'Smileys & People' },
  { name: 'Verified', icon: BadgeCheck, keywords: ['badge', 'check', 'verified', 'approved'], category: 'Smileys & People' },

  // ─── Hearts & Love ───────────────────────────────────────────
  { name: 'Heart', icon: Heart, keywords: ['love', 'like', 'favorite', 'red'], category: 'Hearts & Love' },
  { name: 'Broken Heart', icon: HeartCrack, keywords: ['heartbreak', 'sad', 'crack', 'love'], category: 'Hearts & Love' },
  { name: 'Heart Handshake', icon: HeartHandshake, keywords: ['care', 'partnership', 'trust', 'love'], category: 'Hearts & Love' },
  { name: 'Heart Pulse', icon: HeartPulse, keywords: ['heartbeat', 'health', 'alive', 'love'], category: 'Hearts & Love' },
  { name: 'Sparkles', icon: Sparkles, keywords: ['shine', 'glitter', 'magic', 'new'], category: 'Hearts & Love' },
  { name: 'Sparkle', icon: Sparkle, keywords: ['shine', 'star', 'twinkle', 'bright'], category: 'Hearts & Love' },
  { name: 'Gift', icon: Gift, keywords: ['present', 'birthday', 'surprise', 'box'], category: 'Hearts & Love' },
  { name: 'Gem', icon: Gem, keywords: ['diamond', 'jewel', 'precious', 'stone'], category: 'Hearts & Love' },
  { name: 'Diamond', icon: Diamond, keywords: ['jewel', 'precious', 'luxury', 'ring'], category: 'Hearts & Love' },
  { name: 'Ribbon', icon: Ribbon, keywords: ['bow', 'decoration', 'gift', 'award'], category: 'Hearts & Love' },
  { name: 'Heart Off', icon: HeartOff, keywords: ['dislike', 'unlove', 'broken', 'no'], category: 'Hearts & Love' },
  { name: 'Hand Heart', icon: HandHeart, keywords: ['care', 'give', 'love', 'charity'], category: 'Hearts & Love' },
  { name: 'Love Message', icon: MessageCircleHeart, keywords: ['message', 'love', 'chat', 'heart'], category: 'Hearts & Love' },

  // ─── Animals & Nature ─────────────────────────────────────────
  { name: 'Bird', icon: Bird, keywords: ['animal', 'fly', 'tweet', 'wings'], category: 'Animals & Nature' },
  { name: 'Bug', icon: Bug, keywords: ['insect', 'beetle', 'ladybug', 'nature'], category: 'Animals & Nature' },
  { name: 'Cat', icon: Cat, keywords: ['animal', 'pet', 'kitten', 'meow'], category: 'Animals & Nature' },
  { name: 'Dog', icon: Dog, keywords: ['animal', 'pet', 'puppy', 'woof'], category: 'Animals & Nature' },
  { name: 'Fish', icon: Fish, keywords: ['animal', 'sea', 'ocean', 'swim'], category: 'Animals & Nature' },
  { name: 'Flower', icon: Flower, keywords: ['plant', 'bloom', 'garden', 'rose'], category: 'Animals & Nature' },
  { name: 'Sunflower', icon: Flower2, keywords: ['plant', 'bloom', 'garden', 'yellow'], category: 'Animals & Nature' },
  { name: 'Leaf', icon: Leaf, keywords: ['plant', 'green', 'nature', 'tree'], category: 'Animals & Nature' },
  { name: 'Trees', icon: Trees, keywords: ['forest', 'nature', 'woods', 'green'], category: 'Animals & Nature' },
  { name: 'Sprout', icon: Sprout, keywords: ['plant', 'grow', 'seedling', 'new'], category: 'Animals & Nature' },
  { name: 'Pine Tree', icon: TreePine, keywords: ['tree', 'christmas', 'evergreen', 'forest'], category: 'Animals & Nature' },
  { name: 'Turtle', icon: Turtle, keywords: ['animal', 'slow', 'shell', 'reptile'], category: 'Animals & Nature' },
  { name: 'Rabbit', icon: Rabbit, keywords: ['animal', 'bunny', 'pet', 'hop'], category: 'Animals & Nature' },
  { name: 'Squirrel', icon: Squirrel, keywords: ['animal', 'nut', 'rodent', 'forest'], category: 'Animals & Nature' },
  { name: 'Snail', icon: Snail, keywords: ['animal', 'slow', 'shell', 'slug'], category: 'Animals & Nature' },
  { name: 'Paw Print', icon: PawPrint, keywords: ['animal', 'pet', 'foot', 'track'], category: 'Animals & Nature' },
  { name: 'Deciduous Tree', icon: TreeDeciduous, keywords: ['tree', 'oak', 'nature', 'park'], category: 'Animals & Nature' },
  { name: 'Shrub', icon: Shrub, keywords: ['bush', 'plant', 'hedge', 'garden'], category: 'Animals & Nature' },
  { name: 'Snowy Mountain', icon: MountainSnow, keywords: ['mountain', 'snow', 'winter', 'peak'], category: 'Animals & Nature' },
  { name: 'Waves', icon: Waves, keywords: ['ocean', 'sea', 'water', 'surf'], category: 'Animals & Nature' },
  { name: 'Droplets', icon: Droplets, keywords: ['water', 'rain', 'wet', 'drops'], category: 'Animals & Nature' },
  { name: 'Droplet', icon: Droplet, keywords: ['water', 'rain', 'tear', 'drop'], category: 'Animals & Nature' },
  { name: 'Shell', icon: Shell, keywords: ['sea', 'beach', 'ocean', 'seashell'], category: 'Animals & Nature' },
  { name: 'Wheat', icon: Wheat, keywords: ['grain', 'farm', 'harvest', 'crop'], category: 'Animals & Nature' },
  { name: 'Vegan', icon: Vegan, keywords: ['plant', 'vegetarian', 'leaf', 'organic'], category: 'Animals & Nature' },

  // ─── Food & Drink ─────────────────────────────────────────────
  { name: 'Apple', icon: Apple, keywords: ['fruit', 'food', 'healthy', 'red'], category: 'Food & Drink' },
  { name: 'Cherry', icon: Cherry, keywords: ['fruit', 'food', 'berry', 'red'], category: 'Food & Drink' },
  { name: 'Grape', icon: Grape, keywords: ['fruit', 'food', 'wine', 'purple'], category: 'Food & Drink' },
  { name: 'Banana', icon: Banana, keywords: ['fruit', 'food', 'yellow', 'monkey'], category: 'Food & Drink' },
  { name: 'Coffee', icon: Coffee, keywords: ['drink', 'cafe', 'morning', 'cup'], category: 'Food & Drink' },
  { name: 'Wine', icon: Wine, keywords: ['drink', 'alcohol', 'glass', 'grape'], category: 'Food & Drink' },
  { name: 'Beer', icon: Beer, keywords: ['drink', 'alcohol', 'mug', 'pub'], category: 'Food & Drink' },
  { name: 'Pizza', icon: Pizza, keywords: ['food', 'slice', 'italian', 'cheese'], category: 'Food & Drink' },
  { name: 'Cake', icon: Cake, keywords: ['food', 'dessert', 'birthday', 'sweet'], category: 'Food & Drink' },
  { name: 'Cake Slice', icon: CakeSlice, keywords: ['food', 'dessert', 'pie', 'sweet'], category: 'Food & Drink' },
  { name: 'Ice Cream', icon: IceCreamCone, keywords: ['food', 'dessert', 'cold', 'sweet'], category: 'Food & Drink' },
  { name: 'Cookie', icon: Cookie, keywords: ['food', 'dessert', 'biscuit', 'sweet'], category: 'Food & Drink' },
  { name: 'Croissant', icon: Croissant, keywords: ['food', 'bread', 'french', 'pastry'], category: 'Food & Drink' },
  { name: 'Popcorn', icon: Popcorn, keywords: ['food', 'snack', 'movie', 'cinema'], category: 'Food & Drink' },
  { name: 'Candy', icon: Candy, keywords: ['food', 'sweet', 'sugar', 'treat'], category: 'Food & Drink' },
  { name: 'Milk', icon: Milk, keywords: ['drink', 'dairy', 'white', 'glass'], category: 'Food & Drink' },
  { name: 'Soda', icon: CupSoda, keywords: ['drink', 'soda', 'pop', 'cup'], category: 'Food & Drink' },
  { name: 'Beef', icon: Beef, keywords: ['meat', 'steak', 'food', 'protein'], category: 'Food & Drink' },
  { name: 'Egg', icon: Egg, keywords: ['food', 'breakfast', 'chicken', 'protein'], category: 'Food & Drink' },
  { name: 'Sandwich', icon: Sandwich, keywords: ['food', 'bread', 'lunch', 'meal'], category: 'Food & Drink' },
  { name: 'Salad', icon: Salad, keywords: ['food', 'healthy', 'green', 'vegetable'], category: 'Food & Drink' },
  { name: 'Soup', icon: Soup, keywords: ['food', 'hot', 'bowl', 'meal'], category: 'Food & Drink' },
  { name: 'Nut', icon: Nut, keywords: ['food', 'snack', 'peanut', 'almond'], category: 'Food & Drink' },
  { name: 'Citrus', icon: Citrus, keywords: ['fruit', 'orange', 'lemon', 'lime'], category: 'Food & Drink' },
  { name: 'Glass of Water', icon: GlassWater, keywords: ['drink', 'water', 'glass', 'hydrate'], category: 'Food & Drink' },

  // ─── Travel & Places ──────────────────────────────────────────
  { name: 'Plane', icon: Plane, keywords: ['travel', 'fly', 'airplane', 'flight'], category: 'Travel & Places' },
  { name: 'Car', icon: Car, keywords: ['travel', 'drive', 'vehicle', 'auto'], category: 'Travel & Places' },
  { name: 'Ship', icon: Ship, keywords: ['travel', 'boat', 'sea', 'sail'], category: 'Travel & Places' },
  { name: 'Train', icon: TrainFront, keywords: ['travel', 'railway', 'rail', 'transit'], category: 'Travel & Places' },
  { name: 'Bike', icon: Bike, keywords: ['travel', 'cycle', 'bicycle', 'ride'], category: 'Travel & Places' },
  { name: 'Globe', icon: Globe, keywords: ['world', 'earth', 'planet', 'international'], category: 'Travel & Places' },
  { name: 'Map', icon: Map, keywords: ['navigate', 'direction', 'location', 'atlas'], category: 'Travel & Places' },
  { name: 'Map Pin', icon: MapPin, keywords: ['location', 'place', 'marker', 'pin'], category: 'Travel & Places' },
  { name: 'Mountain', icon: Mountain, keywords: ['nature', 'hiking', 'peak', 'climb'], category: 'Travel & Places' },
  { name: 'Tent', icon: Tent, keywords: ['camping', 'outdoor', 'nature', 'camp'], category: 'Travel & Places' },
  { name: 'Building', icon: Building, keywords: ['city', 'office', 'skyscraper', 'urban'], category: 'Travel & Places' },
  { name: 'Home', icon: Home, keywords: ['house', 'building', 'residence', 'shelter'], category: 'Travel & Places' },
  { name: 'Church', icon: Church, keywords: ['building', 'religion', 'worship', 'temple'], category: 'Travel & Places' },
  { name: 'Compass', icon: Compass, keywords: ['navigate', 'direction', 'north', 'explore'], category: 'Travel & Places' },
  { name: 'Anchor', icon: Anchor, keywords: ['ship', 'sea', 'boat', 'dock'], category: 'Travel & Places' },
  { name: 'Rocket', icon: Rocket, keywords: ['space', 'launch', 'fast', 'spaceship'], category: 'Travel & Places' },
  { name: 'Hotel', icon: Hotel, keywords: ['building', 'lodging', 'sleep', 'travel'], category: 'Travel & Places' },
  { name: 'Factory', icon: Factory, keywords: ['building', 'industry', 'manufacture', 'work'], category: 'Travel & Places' },
  { name: 'Landmark', icon: Landmark, keywords: ['building', 'monument', 'bank', 'government'], category: 'Travel & Places' },
  { name: 'Castle', icon: Castle, keywords: ['building', 'medieval', 'fortress', 'palace'], category: 'Travel & Places' },
  { name: 'Fuel', icon: Fuel, keywords: ['gas', 'petrol', 'station', 'energy'], category: 'Travel & Places' },
  { name: 'Bus', icon: Bus, keywords: ['travel', 'transit', 'public', 'vehicle'], category: 'Travel & Places' },
  { name: 'Sailboat', icon: Sailboat, keywords: ['boat', 'sail', 'sea', 'wind'], category: 'Travel & Places' },
  { name: 'Cable Car', icon: Cable, keywords: ['cable', 'gondola', 'ski', 'mountain'], category: 'Travel & Places' },
  { name: 'Warehouse', icon: Warehouse, keywords: ['building', 'storage', 'depot', 'logistics'], category: 'Travel & Places' },
  { name: 'Store', icon: Store, keywords: ['shop', 'retail', 'buy', 'market'], category: 'Travel & Places' },
  { name: 'Hospital', icon: Hospital, keywords: ['building', 'medical', 'health', 'emergency'], category: 'Travel & Places' },
  { name: 'School', icon: School, keywords: ['building', 'education', 'learn', 'study'], category: 'Travel & Places' },
  { name: 'Library', icon: Library, keywords: ['building', 'books', 'read', 'study'], category: 'Travel & Places' },

  // ─── Activities ───────────────────────────────────────────────
  { name: 'Music', icon: Music, keywords: ['song', 'note', 'melody', 'sound'], category: 'Activities' },
  { name: 'Gamepad', icon: Gamepad2, keywords: ['game', 'play', 'controller', 'gaming'], category: 'Activities' },
  { name: 'Dumbbell', icon: Dumbbell, keywords: ['gym', 'workout', 'fitness', 'exercise'], category: 'Activities' },
  { name: 'Trophy', icon: Trophy, keywords: ['win', 'award', 'champion', 'prize'], category: 'Activities' },
  { name: 'Medal', icon: Medal, keywords: ['award', 'prize', 'achievement', 'gold'], category: 'Activities' },
  { name: 'Target', icon: Target, keywords: ['goal', 'aim', 'bullseye', 'focus'], category: 'Activities' },
  { name: 'Palette', icon: Palette, keywords: ['art', 'paint', 'color', 'creative'], category: 'Activities' },
  { name: 'Camera', icon: Camera, keywords: ['photo', 'picture', 'snap', 'lens'], category: 'Activities' },
  { name: 'Clapperboard', icon: Clapperboard, keywords: ['movie', 'film', 'cinema', 'action'], category: 'Activities' },
  { name: 'Microphone', icon: Mic, keywords: ['sing', 'karaoke', 'record', 'voice'], category: 'Activities' },
  { name: 'Headphones', icon: Headphones, keywords: ['music', 'listen', 'audio', 'sound'], category: 'Activities' },
  { name: 'Guitar', icon: Guitar, keywords: ['music', 'instrument', 'play', 'rock'], category: 'Activities' },
  { name: 'Dice', icon: Dice5, keywords: ['game', 'luck', 'roll', 'random'], category: 'Activities' },
  { name: 'Volleyball', icon: Volleyball, keywords: ['sport', 'ball', 'game', 'beach'], category: 'Activities' },
  { name: 'Paint Brush', icon: Brush, keywords: ['art', 'paint', 'draw', 'creative'], category: 'Activities' },
  { name: 'Pen Tool', icon: PenTool, keywords: ['design', 'draw', 'vector', 'bezier'], category: 'Activities' },
  { name: 'Ruler', icon: Ruler, keywords: ['measure', 'length', 'tool', 'straight'], category: 'Activities' },
  { name: 'Dice One', icon: Dice1, keywords: ['game', 'luck', 'roll', 'one'], category: 'Activities' },
  { name: 'Puzzle', icon: Puzzle, keywords: ['game', 'piece', 'jigsaw', 'solve'], category: 'Activities' },
  { name: 'Drama', icon: Drama, keywords: ['theater', 'masks', 'acting', 'comedy'], category: 'Activities' },
  { name: 'Piano', icon: Piano, keywords: ['music', 'instrument', 'keys', 'play'], category: 'Activities' },
  { name: 'Drum', icon: Drum, keywords: ['music', 'instrument', 'beat', 'rhythm'], category: 'Activities' },
  { name: 'Speaker', icon: Speaker, keywords: ['music', 'sound', 'audio', 'loud'], category: 'Activities' },
  { name: 'Radio', icon: Radio, keywords: ['music', 'broadcast', 'listen', 'fm'], category: 'Activities' },
  { name: 'Television', icon: Tv, keywords: ['tv', 'watch', 'screen', 'show'], category: 'Activities' },
  { name: 'Film', icon: Film, keywords: ['movie', 'cinema', 'reel', 'video'], category: 'Activities' },
  { name: 'Projector', icon: Projector, keywords: ['movie', 'cinema', 'present', 'screen'], category: 'Activities' },

  // ─── Objects ──────────────────────────────────────────────────
  { name: 'Key', icon: Key, keywords: ['lock', 'security', 'access', 'unlock'], category: 'Objects' },
  { name: 'Lock', icon: Lock, keywords: ['security', 'private', 'closed', 'safe'], category: 'Objects' },
  { name: 'Lightbulb', icon: Lightbulb, keywords: ['idea', 'light', 'bright', 'lamp'], category: 'Objects' },
  { name: 'Phone', icon: Phone, keywords: ['call', 'mobile', 'telephone', 'contact'], category: 'Objects' },
  { name: 'Laptop', icon: Laptop, keywords: ['computer', 'device', 'work', 'tech'], category: 'Objects' },
  { name: 'Watch', icon: Watch, keywords: ['time', 'clock', 'wrist', 'accessory'], category: 'Objects' },
  { name: 'Umbrella', icon: Umbrella, keywords: ['rain', 'weather', 'protection', 'cover'], category: 'Objects' },
  { name: 'Scissors', icon: Scissors, keywords: ['cut', 'tool', 'craft', 'trim'], category: 'Objects' },
  { name: 'Wrench', icon: Wrench, keywords: ['tool', 'fix', 'repair', 'settings'], category: 'Objects' },
  { name: 'Hammer', icon: Hammer, keywords: ['tool', 'build', 'construction', 'nail'], category: 'Objects' },
  { name: 'Bell', icon: Bell, keywords: ['notification', 'alert', 'ring', 'alarm'], category: 'Objects' },
  { name: 'Bookmark', icon: Bookmark, keywords: ['save', 'mark', 'favorite', 'tag'], category: 'Objects' },
  { name: 'Flag', icon: Flag, keywords: ['country', 'mark', 'report', 'banner'], category: 'Objects' },
  { name: 'Mail', icon: Mail, keywords: ['email', 'letter', 'message', 'envelope'], category: 'Objects' },
  { name: 'Pencil', icon: Pencil, keywords: ['write', 'edit', 'draw', 'pen'], category: 'Objects' },
  { name: 'Briefcase', icon: Briefcase, keywords: ['work', 'business', 'office', 'job'], category: 'Objects' },
  { name: 'Shirt', icon: Shirt, keywords: ['clothing', 'fashion', 'tshirt', 'wear'], category: 'Objects' },
  { name: 'Wallet', icon: Wallet, keywords: ['money', 'pay', 'cash', 'finance'], category: 'Objects' },
  { name: 'Shopping Bag', icon: ShoppingBag, keywords: ['shop', 'buy', 'retail', 'bag'], category: 'Objects' },
  { name: 'Package', icon: Package, keywords: ['box', 'delivery', 'shipping', 'parcel'], category: 'Objects' },
  { name: 'Syringe', icon: Syringe, keywords: ['medical', 'injection', 'vaccine', 'needle'], category: 'Objects' },
  { name: 'Pill', icon: Pill, keywords: ['medical', 'medicine', 'drug', 'tablet'], category: 'Objects' },
  { name: 'Stethoscope', icon: Stethoscope, keywords: ['medical', 'doctor', 'health', 'checkup'], category: 'Objects' },
  { name: 'Scroll', icon: Scroll, keywords: ['paper', 'document', 'ancient', 'parchment'], category: 'Objects' },
  { name: 'Newspaper', icon: Newspaper, keywords: ['news', 'press', 'article', 'media'], category: 'Objects' },
  { name: 'Book Open', icon: BookOpen, keywords: ['read', 'study', 'learn', 'literature'], category: 'Objects' },
  { name: 'Notebook', icon: Notebook, keywords: ['write', 'notes', 'journal', 'diary'], category: 'Objects' },
  { name: 'File', icon: FileText, keywords: ['document', 'text', 'paper', 'page'], category: 'Objects' },
  { name: 'Clipboard', icon: Clipboard, keywords: ['copy', 'paste', 'board', 'task'], category: 'Objects' },

  // ─── Symbols ──────────────────────────────────────────────────
  { name: 'Star', icon: Star, keywords: ['favorite', 'rate', 'shine', 'night'], category: 'Symbols' },
  { name: 'Sun', icon: Sun, keywords: ['bright', 'day', 'weather', 'warm'], category: 'Symbols' },
  { name: 'Moon', icon: Moon, keywords: ['night', 'dark', 'sleep', 'crescent'], category: 'Symbols' },
  { name: 'Cloud', icon: Cloud, keywords: ['weather', 'sky', 'storage', 'fluffy'], category: 'Symbols' },
  { name: 'Zap', icon: Zap, keywords: ['lightning', 'electric', 'power', 'fast'], category: 'Symbols' },
  { name: 'Flame', icon: Flame, keywords: ['fire', 'hot', 'burn', 'trending'], category: 'Symbols' },
  { name: 'Snowflake', icon: Snowflake, keywords: ['cold', 'winter', 'ice', 'freeze'], category: 'Symbols' },
  { name: 'Rainbow', icon: Rainbow, keywords: ['color', 'pride', 'arc', 'weather'], category: 'Symbols' },
  { name: 'Infinity', icon: Infinity, keywords: ['forever', 'loop', 'endless', 'math'], category: 'Symbols' },
  { name: 'Hash', icon: Hash, keywords: ['number', 'tag', 'hashtag', 'pound'], category: 'Symbols' },
  { name: 'At Sign', icon: AtSign, keywords: ['email', 'mention', 'address', 'at'], category: 'Symbols' },
  { name: 'Copyright', icon: Copyright, keywords: ['legal', 'rights', 'symbol', 'law'], category: 'Symbols' },
  { name: 'Pi', icon: Pi, keywords: ['math', 'number', 'greek', 'constant'], category: 'Symbols' },
  { name: 'Omega', icon: Omega, keywords: ['greek', 'last', 'end', 'letter'], category: 'Symbols' },
  { name: 'Percent', icon: Percent, keywords: ['math', 'discount', 'rate', 'number'], category: 'Symbols' },
  { name: 'Warning', icon: AlertTriangle, keywords: ['alert', 'danger', 'caution', 'error'], category: 'Symbols' },
  { name: 'Circle', icon: Circle, keywords: ['shape', 'round', 'dot', 'ring'], category: 'Symbols' },
  { name: 'Square', icon: Square, keywords: ['shape', 'box', 'rectangle', 'block'], category: 'Symbols' },
  { name: 'Triangle', icon: Triangle, keywords: ['shape', 'delta', 'play', 'arrow'], category: 'Symbols' },
  { name: 'Pentagon', icon: Pentagon, keywords: ['shape', 'polygon', 'five', 'sides'], category: 'Symbols' },
  { name: 'Hexagon', icon: Hexagon, keywords: ['shape', 'polygon', 'six', 'honeycomb'], category: 'Symbols' },
  { name: 'Octagon', icon: Octagon, keywords: ['shape', 'stop', 'eight', 'polygon'], category: 'Symbols' },
  { name: 'Arrow Up', icon: ArrowUp, keywords: ['up', 'direction', 'north', 'top'], category: 'Symbols' },
  { name: 'Arrow Right', icon: ArrowRight, keywords: ['right', 'direction', 'east', 'next'], category: 'Symbols' },
  { name: 'Check', icon: Check, keywords: ['yes', 'done', 'correct', 'tick'], category: 'Symbols' },
  { name: 'Cross', icon: X, keywords: ['no', 'close', 'delete', 'remove'], category: 'Symbols' },
  { name: 'Plus', icon: Plus, keywords: ['add', 'new', 'create', 'positive'], category: 'Symbols' },
  { name: 'Minus', icon: Minus, keywords: ['subtract', 'remove', 'less', 'negative'], category: 'Symbols' },
  { name: 'Equal', icon: Equal, keywords: ['math', 'same', 'balance', 'equation'], category: 'Symbols' },
  { name: 'Asterisk', icon: Asterisk, keywords: ['star', 'multiply', 'note', 'required'], category: 'Symbols' },
  { name: 'Power', icon: Power, keywords: ['on', 'off', 'switch', 'button'], category: 'Symbols' },
  { name: 'Wifi', icon: Wifi, keywords: ['internet', 'wireless', 'signal', 'connect'], category: 'Symbols' },
  { name: 'Bluetooth', icon: Bluetooth, keywords: ['wireless', 'connect', 'pair', 'device'], category: 'Symbols' },
  { name: 'Volume', icon: Volume2, keywords: ['sound', 'audio', 'speaker', 'loud'], category: 'Symbols' },
  { name: 'Eye', icon: Eye, keywords: ['see', 'look', 'view', 'visible'], category: 'Symbols' },
  { name: 'Eye Off', icon: EyeOff, keywords: ['hide', 'invisible', 'blind', 'hidden'], category: 'Symbols' },
  { name: 'Shield', icon: Shield, keywords: ['security', 'protect', 'safe', 'defense'], category: 'Symbols' },
  { name: 'Unlock', icon: Unlock, keywords: ['open', 'access', 'security', 'free'], category: 'Symbols' },
  { name: 'Clock', icon: Clock, keywords: ['time', 'hour', 'watch', 'schedule'], category: 'Symbols' },
  { name: 'Timer', icon: Timer, keywords: ['time', 'countdown', 'stopwatch', 'alarm'], category: 'Symbols' },
  { name: 'Calendar', icon: Calendar, keywords: ['date', 'schedule', 'month', 'event'], category: 'Symbols' },
];
