import {
  // Smileys & People
  Smile,
  Laugh,
  SmilePlus,
  Meh,
  Frown,
  Angry,
  Annoyed,
  Ghost,
  Baby,
  User,
  Users,
  Crown,
  Glasses,
  PartyPopper,
  Skull,
  BotMessageSquare,

  // Hearts & Love
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Sparkles,
  Gift,
  Gem,
  Diamond,
  Ribbon,
  HeartOff,
  Sparkle,

  // Animals & Nature
  Bird,
  Bug,
  Cat,
  Dog,
  Fish,
  Flower,
  Flower2,
  Leaf,
  Trees,
  Sprout,
  TreePine,
  Turtle,
  Rabbit,
  Squirrel,
  Snail,
  PawPrint,

  // Food & Drink
  Apple,
  Cherry,
  Grape,
  Banana,
  Coffee,
  Wine,
  Beer,
  Pizza,
  Cake,
  CakeSlice,
  IceCreamCone,
  Cookie,
  Croissant,
  Popcorn,
  Candy,
  Milk,

  // Travel & Places
  Plane,
  Car,
  Ship,
  TrainFront,
  Bike,
  Globe,
  Map,
  MapPin,
  Mountain,
  Tent,
  Building,
  Home,
  Church,
  Compass,
  Anchor,
  Rocket,

  // Activities
  Music,
  Gamepad2,
  Dumbbell,
  Trophy,
  Medal,
  Target,
  Palette,
  Camera,
  Clapperboard,
  Mic,
  Headphones,
  Guitar,
  Dice5,
  Volleyball,

  // Objects
  Key,
  Lock,
  Lightbulb,
  Phone,
  Laptop,
  Watch,
  Umbrella,
  Scissors,
  Wrench,
  Hammer,
  Bell,
  Bookmark,
  Flag,
  Mail,
  Pencil,
  Briefcase,

  // Symbols
  Star,
  Sun,
  Moon,
  Cloud,
  Zap,
  Flame,
  Snowflake,
  Rainbow,
  Infinity,
  Hash,
  AtSign,
  Copyright,
  Pi,
  Omega,
  Percent,
  AlertTriangle,
} from 'lucide-react';

import type { EmojiEntry, EmojiCategory } from './types';

export const CATEGORIES: EmojiCategory[] = [
  'Smileys & People',
  'Hearts & Love',
  'Animals & Nature',
  'Food & Drink',
  'Travel & Places',
  'Activities',
  'Objects',
  'Symbols',
];

export const CATEGORY_ICONS: Record<EmojiCategory, typeof Smile> = {
  'Smileys & People': Smile,
  'Hearts & Love': Heart,
  'Animals & Nature': Leaf,
  'Food & Drink': Coffee,
  'Travel & Places': Globe,
  'Activities': Music,
  'Objects': Key,
  'Symbols': Star,
};

export const emojiData: EmojiEntry[] = [
  // ─── Smileys & People ────────────────────────────────────────
  { name: 'Smile', icon: Smile, keywords: ['happy', 'face', 'smiley', 'grin'], category: 'Smileys & People' },
  { name: 'Laugh', icon: Laugh, keywords: ['lol', 'haha', 'funny', 'joy'], category: 'Smileys & People' },
  { name: 'Smile Plus', icon: SmilePlus, keywords: ['add', 'happy', 'new', 'positive'], category: 'Smileys & People' },
  { name: 'Meh', icon: Meh, keywords: ['neutral', 'indifferent', 'okay', 'face'], category: 'Smileys & People' },
  { name: 'Frown', icon: Frown, keywords: ['sad', 'unhappy', 'disappointed', 'face'], category: 'Smileys & People' },
  { name: 'Angry', icon: Angry, keywords: ['mad', 'upset', 'furious', 'face'], category: 'Smileys & People' },
  { name: 'Annoyed', icon: Annoyed, keywords: ['irritated', 'frustrated', 'face'], category: 'Smileys & People' },
  { name: 'Ghost', icon: Ghost, keywords: ['spooky', 'halloween', 'spirit', 'boo'], category: 'Smileys & People' },
  { name: 'Baby', icon: Baby, keywords: ['child', 'infant', 'kid', 'newborn'], category: 'Smileys & People' },
  { name: 'User', icon: User, keywords: ['person', 'profile', 'account', 'human'], category: 'Smileys & People' },
  { name: 'Users', icon: Users, keywords: ['people', 'group', 'team', 'community'], category: 'Smileys & People' },
  { name: 'Crown', icon: Crown, keywords: ['king', 'queen', 'royal', 'winner'], category: 'Smileys & People' },
  { name: 'Glasses', icon: Glasses, keywords: ['nerd', 'smart', 'vision', 'cool'], category: 'Smileys & People' },
  { name: 'Party Popper', icon: PartyPopper, keywords: ['celebrate', 'celebration', 'confetti', 'tada'], category: 'Smileys & People' },
  { name: 'Skull', icon: Skull, keywords: ['dead', 'danger', 'death', 'skeleton'], category: 'Smileys & People' },
  { name: 'Bot', icon: BotMessageSquare, keywords: ['robot', 'ai', 'machine', 'chat'], category: 'Smileys & People' },

  // ─── Hearts & Love ───────────────────────────────────────────
  { name: 'Heart', icon: Heart, keywords: ['love', 'like', 'favorite', 'red'], category: 'Hearts & Love' },
  { name: 'Broken Heart', icon: HeartCrack, keywords: ['heartbreak', 'sad', 'crack', 'love'], category: 'Hearts & Love' },
  { name: 'Heart Handshake', icon: HeartHandshake, keywords: ['care', 'partnership', 'trust', 'love'], category: 'Hearts & Love' },
  { name: 'Heart Pulse', icon: HeartPulse, keywords: ['heartbeat', 'health', 'alive', 'love'], category: 'Hearts & Love' },
  { name: 'Sparkles', icon: Sparkles, keywords: ['shine', 'glitter', 'magic', 'new'], category: 'Hearts & Love' },
  { name: 'Sparkle', icon: Sparkle, keywords: ['shine', 'star', 'twinkle', 'bright'], category: 'Hearts & Love' },
  { name: 'Gift', icon: Gift, keywords: ['present', 'birthday', 'surprise', 'box'], category: 'Hearts & Love' },
  { name: 'Gem', icon: Gem, keywords: ['diamond', 'jewel', 'precious', 'stone'], category: 'Hearts & Love' },
  { name: 'Diamond', icon: Diamond, keywords: ['jewel', 'precious', 'luxury', 'ring'], category: 'Hearts & Love' },
  { name: 'Ribbon', icon: Ribbon, keywords: ['bow', 'decoration', 'gift', 'award'], category: 'Hearts & Love' },
  { name: 'Heart Off', icon: HeartOff, keywords: ['dislike', 'unlove', 'broken', 'no'], category: 'Hearts & Love' },

  // ─── Animals & Nature ─────────────────────────────────────────
  { name: 'Bird', icon: Bird, keywords: ['animal', 'fly', 'tweet', 'wings'], category: 'Animals & Nature' },
  { name: 'Bug', icon: Bug, keywords: ['insect', 'beetle', 'ladybug', 'nature'], category: 'Animals & Nature' },
  { name: 'Cat', icon: Cat, keywords: ['animal', 'pet', 'kitten', 'meow'], category: 'Animals & Nature' },
  { name: 'Dog', icon: Dog, keywords: ['animal', 'pet', 'puppy', 'woof'], category: 'Animals & Nature' },
  { name: 'Fish', icon: Fish, keywords: ['animal', 'sea', 'ocean', 'swim'], category: 'Animals & Nature' },
  { name: 'Flower', icon: Flower, keywords: ['plant', 'bloom', 'garden', 'rose'], category: 'Animals & Nature' },
  { name: 'Sunflower', icon: Flower2, keywords: ['plant', 'bloom', 'garden', 'yellow'], category: 'Animals & Nature' },
  { name: 'Leaf', icon: Leaf, keywords: ['plant', 'green', 'nature', 'tree'], category: 'Animals & Nature' },
  { name: 'Trees', icon: Trees, keywords: ['forest', 'nature', 'woods', 'green'], category: 'Animals & Nature' },
  { name: 'Sprout', icon: Sprout, keywords: ['plant', 'grow', 'seedling', 'new'], category: 'Animals & Nature' },
  { name: 'Pine Tree', icon: TreePine, keywords: ['tree', 'christmas', 'evergreen', 'forest'], category: 'Animals & Nature' },
  { name: 'Turtle', icon: Turtle, keywords: ['animal', 'slow', 'shell', 'reptile'], category: 'Animals & Nature' },
  { name: 'Rabbit', icon: Rabbit, keywords: ['animal', 'bunny', 'pet', 'hop'], category: 'Animals & Nature' },
  { name: 'Squirrel', icon: Squirrel, keywords: ['animal', 'nut', 'rodent', 'forest'], category: 'Animals & Nature' },
  { name: 'Snail', icon: Snail, keywords: ['animal', 'slow', 'shell', 'slug'], category: 'Animals & Nature' },
  { name: 'Paw Print', icon: PawPrint, keywords: ['animal', 'pet', 'foot', 'track'], category: 'Animals & Nature' },

  // ─── Food & Drink ─────────────────────────────────────────────
  { name: 'Apple', icon: Apple, keywords: ['fruit', 'food', 'healthy', 'red'], category: 'Food & Drink' },
  { name: 'Cherry', icon: Cherry, keywords: ['fruit', 'food', 'berry', 'red'], category: 'Food & Drink' },
  { name: 'Grape', icon: Grape, keywords: ['fruit', 'food', 'wine', 'purple'], category: 'Food & Drink' },
  { name: 'Banana', icon: Banana, keywords: ['fruit', 'food', 'yellow', 'monkey'], category: 'Food & Drink' },
  { name: 'Coffee', icon: Coffee, keywords: ['drink', 'cafe', 'morning', 'cup'], category: 'Food & Drink' },
  { name: 'Wine', icon: Wine, keywords: ['drink', 'alcohol', 'glass', 'grape'], category: 'Food & Drink' },
  { name: 'Beer', icon: Beer, keywords: ['drink', 'alcohol', 'mug', 'pub'], category: 'Food & Drink' },
  { name: 'Pizza', icon: Pizza, keywords: ['food', 'slice', 'italian', 'cheese'], category: 'Food & Drink' },
  { name: 'Cake', icon: Cake, keywords: ['food', 'dessert', 'birthday', 'sweet'], category: 'Food & Drink' },
  { name: 'Cake Slice', icon: CakeSlice, keywords: ['food', 'dessert', 'pie', 'sweet'], category: 'Food & Drink' },
  { name: 'Ice Cream', icon: IceCreamCone, keywords: ['food', 'dessert', 'cold', 'sweet'], category: 'Food & Drink' },
  { name: 'Cookie', icon: Cookie, keywords: ['food', 'dessert', 'biscuit', 'sweet'], category: 'Food & Drink' },
  { name: 'Croissant', icon: Croissant, keywords: ['food', 'bread', 'french', 'pastry'], category: 'Food & Drink' },
  { name: 'Popcorn', icon: Popcorn, keywords: ['food', 'snack', 'movie', 'cinema'], category: 'Food & Drink' },
  { name: 'Candy', icon: Candy, keywords: ['food', 'sweet', 'sugar', 'treat'], category: 'Food & Drink' },
  { name: 'Milk', icon: Milk, keywords: ['drink', 'dairy', 'white', 'glass'], category: 'Food & Drink' },

  // ─── Travel & Places ──────────────────────────────────────────
  { name: 'Plane', icon: Plane, keywords: ['travel', 'fly', 'airplane', 'flight'], category: 'Travel & Places' },
  { name: 'Car', icon: Car, keywords: ['travel', 'drive', 'vehicle', 'auto'], category: 'Travel & Places' },
  { name: 'Ship', icon: Ship, keywords: ['travel', 'boat', 'sea', 'sail'], category: 'Travel & Places' },
  { name: 'Train', icon: TrainFront, keywords: ['travel', 'railway', 'rail', 'transit'], category: 'Travel & Places' },
  { name: 'Bike', icon: Bike, keywords: ['travel', 'cycle', 'bicycle', 'ride'], category: 'Travel & Places' },
  { name: 'Globe', icon: Globe, keywords: ['world', 'earth', 'planet', 'international'], category: 'Travel & Places' },
  { name: 'Map', icon: Map, keywords: ['navigate', 'direction', 'location', 'atlas'], category: 'Travel & Places' },
  { name: 'Map Pin', icon: MapPin, keywords: ['location', 'place', 'marker', 'pin'], category: 'Travel & Places' },
  { name: 'Mountain', icon: Mountain, keywords: ['nature', 'hiking', 'peak', 'climb'], category: 'Travel & Places' },
  { name: 'Tent', icon: Tent, keywords: ['camping', 'outdoor', 'nature', 'camp'], category: 'Travel & Places' },
  { name: 'Building', icon: Building, keywords: ['city', 'office', 'skyscraper', 'urban'], category: 'Travel & Places' },
  { name: 'Home', icon: Home, keywords: ['house', 'building', 'residence', 'shelter'], category: 'Travel & Places' },
  { name: 'Church', icon: Church, keywords: ['building', 'religion', 'worship', 'temple'], category: 'Travel & Places' },
  { name: 'Compass', icon: Compass, keywords: ['navigate', 'direction', 'north', 'explore'], category: 'Travel & Places' },
  { name: 'Anchor', icon: Anchor, keywords: ['ship', 'sea', 'boat', 'dock'], category: 'Travel & Places' },
  { name: 'Rocket', icon: Rocket, keywords: ['space', 'launch', 'fast', 'spaceship'], category: 'Travel & Places' },

  // ─── Activities ───────────────────────────────────────────────
  { name: 'Music', icon: Music, keywords: ['song', 'note', 'melody', 'sound'], category: 'Activities' },
  { name: 'Gamepad', icon: Gamepad2, keywords: ['game', 'play', 'controller', 'gaming'], category: 'Activities' },
  { name: 'Dumbbell', icon: Dumbbell, keywords: ['gym', 'workout', 'fitness', 'exercise'], category: 'Activities' },
  { name: 'Trophy', icon: Trophy, keywords: ['win', 'award', 'champion', 'prize'], category: 'Activities' },
  { name: 'Medal', icon: Medal, keywords: ['award', 'prize', 'achievement', 'gold'], category: 'Activities' },
  { name: 'Target', icon: Target, keywords: ['goal', 'aim', 'bullseye', 'focus'], category: 'Activities' },
  { name: 'Palette', icon: Palette, keywords: ['art', 'paint', 'color', 'creative'], category: 'Activities' },
  { name: 'Camera', icon: Camera, keywords: ['photo', 'picture', 'snap', 'lens'], category: 'Activities' },
  { name: 'Clapperboard', icon: Clapperboard, keywords: ['movie', 'film', 'cinema', 'action'], category: 'Activities' },
  { name: 'Microphone', icon: Mic, keywords: ['sing', 'karaoke', 'record', 'voice'], category: 'Activities' },
  { name: 'Headphones', icon: Headphones, keywords: ['music', 'listen', 'audio', 'sound'], category: 'Activities' },
  { name: 'Guitar', icon: Guitar, keywords: ['music', 'instrument', 'play', 'rock'], category: 'Activities' },
  { name: 'Dice', icon: Dice5, keywords: ['game', 'luck', 'roll', 'random'], category: 'Activities' },
  { name: 'Volleyball', icon: Volleyball, keywords: ['sport', 'ball', 'game', 'beach'], category: 'Activities' },

  // ─── Objects ──────────────────────────────────────────────────
  { name: 'Key', icon: Key, keywords: ['lock', 'security', 'access', 'unlock'], category: 'Objects' },
  { name: 'Lock', icon: Lock, keywords: ['security', 'private', 'closed', 'safe'], category: 'Objects' },
  { name: 'Lightbulb', icon: Lightbulb, keywords: ['idea', 'light', 'bright', 'lamp'], category: 'Objects' },
  { name: 'Phone', icon: Phone, keywords: ['call', 'mobile', 'telephone', 'contact'], category: 'Objects' },
  { name: 'Laptop', icon: Laptop, keywords: ['computer', 'device', 'work', 'tech'], category: 'Objects' },
  { name: 'Watch', icon: Watch, keywords: ['time', 'clock', 'wrist', 'accessory'], category: 'Objects' },
  { name: 'Umbrella', icon: Umbrella, keywords: ['rain', 'weather', 'protection', 'cover'], category: 'Objects' },
  { name: 'Scissors', icon: Scissors, keywords: ['cut', 'tool', 'craft', 'trim'], category: 'Objects' },
  { name: 'Wrench', icon: Wrench, keywords: ['tool', 'fix', 'repair', 'settings'], category: 'Objects' },
  { name: 'Hammer', icon: Hammer, keywords: ['tool', 'build', 'construction', 'nail'], category: 'Objects' },
  { name: 'Bell', icon: Bell, keywords: ['notification', 'alert', 'ring', 'alarm'], category: 'Objects' },
  { name: 'Bookmark', icon: Bookmark, keywords: ['save', 'mark', 'favorite', 'tag'], category: 'Objects' },
  { name: 'Flag', icon: Flag, keywords: ['country', 'mark', 'report', 'banner'], category: 'Objects' },
  { name: 'Mail', icon: Mail, keywords: ['email', 'letter', 'message', 'envelope'], category: 'Objects' },
  { name: 'Pencil', icon: Pencil, keywords: ['write', 'edit', 'draw', 'pen'], category: 'Objects' },
  { name: 'Briefcase', icon: Briefcase, keywords: ['work', 'business', 'office', 'job'], category: 'Objects' },

  // ─── Symbols ──────────────────────────────────────────────────
  { name: 'Star', icon: Star, keywords: ['favorite', 'rate', 'shine', 'night'], category: 'Symbols' },
  { name: 'Sun', icon: Sun, keywords: ['bright', 'day', 'weather', 'warm'], category: 'Symbols' },
  { name: 'Moon', icon: Moon, keywords: ['night', 'dark', 'sleep', 'crescent'], category: 'Symbols' },
  { name: 'Cloud', icon: Cloud, keywords: ['weather', 'sky', 'storage', 'fluffy'], category: 'Symbols' },
  { name: 'Zap', icon: Zap, keywords: ['lightning', 'electric', 'power', 'fast'], category: 'Symbols' },
  { name: 'Flame', icon: Flame, keywords: ['fire', 'hot', 'burn', 'trending'], category: 'Symbols' },
  { name: 'Snowflake', icon: Snowflake, keywords: ['cold', 'winter', 'ice', 'freeze'], category: 'Symbols' },
  { name: 'Rainbow', icon: Rainbow, keywords: ['color', 'pride', 'arc', 'weather'], category: 'Symbols' },
  { name: 'Infinity', icon: Infinity, keywords: ['forever', 'loop', 'endless', 'math'], category: 'Symbols' },
  { name: 'Hash', icon: Hash, keywords: ['number', 'tag', 'hashtag', 'pound'], category: 'Symbols' },
  { name: 'At Sign', icon: AtSign, keywords: ['email', 'mention', 'address', 'at'], category: 'Symbols' },
  { name: 'Copyright', icon: Copyright, keywords: ['legal', 'rights', 'symbol', 'law'], category: 'Symbols' },
  { name: 'Pi', icon: Pi, keywords: ['math', 'number', 'greek', 'constant'], category: 'Symbols' },
  { name: 'Omega', icon: Omega, keywords: ['greek', 'last', 'end', 'letter'], category: 'Symbols' },
  { name: 'Percent', icon: Percent, keywords: ['math', 'discount', 'rate', 'number'], category: 'Symbols' },
  { name: 'Warning', icon: AlertTriangle, keywords: ['alert', 'danger', 'caution', 'error'], category: 'Symbols' },
];
